{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "estafette-google-cloud-dns.fullname" . }}
  labels:
{{ include "estafette-google-cloud-dns.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "estafette-google-cloud-dns.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "estafette-google-cloud-dns.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
