{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "estafette-google-cloud-dns.serviceAccountName" . }}
  
  labels:
{{ include "estafette-google-cloud-dns.labels" . | indent 4 }}
{{- end -}}
