apiVersion: v1
appVersion: "1.0"
description: Kubernetes controller to update dns record in a Google Cloud DNS zone for annotated services and ingresses
name: estafette-google-cloud-dns
version: 0.1.0
home: https://helm.estafette.io
icon: https://helm.estafette.io/icon.png
